baseURL = "https://thesis.science.upjs.sk/~jduras/"
languageCode = "en-us"
title = "Jakub Duras Bachelor Thesis"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "./"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "./posts"
    weight = 2
[[menu.main]]
    name = "Progress"
    url = "./progress"
    weight = 3
[[menu.main]]
    name = "Draft"
    url = "./draft"
    weight = 4

[params]
    description = "A website built through Hugo."
    footer = "&copy; [Jakub Duras](https://duras.me) 2019 | [Github](https://github.com/durasj)"
