name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
    - name: Build website
      run: hugo --minify
    - name: Compile LaTeX thesis
      uses: xu-cheng/latex-action@master
      with:
        working_directory: paper
        root_file: main.tex
    - name: Copy PDF thesis
      run: cp paper/main.pdf public/draft.pdf

    - name: Deploy to Netlify
      uses: jsmrcaga/action-netlify-deploy@v1.2.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        build_directory: public
